apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: roadmap
  labels:
    app: promtail
    app.kubernetes.io/name: roadmap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: promtail
  namespace: roadmap
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "nodes/proxy"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promtail
  namespace: roadmap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: roadmap
